### PR TITLE
Use github actions for CI

### PR DESCRIPTION
**Pull request by shenki**
Signed-off-by: Joel Stanley <joel@jms.id.au>

### CODE REVIEW

**Comment by sharkcz** [comment]
IMO the libpdbg.h change should be in a separate commit.

**Comment by shenki** [comment]
> IMO the libpdbg.h change should be in a separate commit.

It should not be there at all! Thanks for catching that.

**Comment by mikey** [comment]
Thanks @shenki

**Comment by mikey** [comment]
Seems to have worked!
https://github.com/open-power/pdbg/runs/3695301873

**Pull request merged**
